[package]
name = "terminal_hundred_days"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
ratatui = "0.23.0"
crossterm = "0.27.0"
