[package]
name = "terminal_hundred_days"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
ratatui = { git = "https://github.com/ratatui-org/ratatui" }
crossterm = "0.27.0"
